name: Main Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '.circleci/**'
      - '.github/**'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        java_version: ['8', '11', '15']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - uses: actions/cache@v2.1.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run tests
      run: ./mvnw -V -B -ntp -ff clean verify
    - name: Release Snapshot
      if: matrix.java_version == '11'
      run: ./mvnw -V -B -ntp -ff deploy
